DROP TABLE IF EXISTS cookies; 
DROP TABLE IF EXISTS pallets;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS order_sizes;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS materials;



